### ISSUE TITLE
實習交接文件

### ISSUE THREAD

**Issue by toomore** [ocftw/OSCVPass#36]
結束實習前目前我們的進度到哪個部分。

1. 目前手邊的進度。
2. 未來可以持續的項目。
3. 其他：試過但沒有成果的項目。

**Comment by ChAoSUnItY** [comment]
共筆：https://hackmd.io/@chaos-unity/B1lVrbia2

**Comment by toomore** [comment]
新增到文件「實習紀錄」 https://github.com/ocftw/OSCVPass/commit/4ba936b8a525d703ea468669c03ffe0a14bc03c4
